import os
import requests

from review_bot import review_code


GITHUB_API = "https://api.github.com"


def get_headers():

    token = os.getenv("GITHUB_TOKEN")

    if not token:
        raise RuntimeError(
            "GITHUB_TOKEN environment variable is not set."
        )

    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }


def detect_language(filename):

    extension = os.path.splitext(
        filename
    )[1].lower()

    languages = {
        ".c": "C",
        ".h": "C",
        ".cpp": "C++",
        ".cc": "C++",
        ".cxx": "C++",
        ".hpp": "C++",
        ".java": "Java"
    }

    return languages.get(extension)


def get_pull_request_files(
    owner,
    repo,
    pull_number
):

    url = (
        f"{GITHUB_API}/repos/"
        f"{owner}/{repo}/pulls/"
        f"{pull_number}/files"
    )

    response = requests.get(
        url,
        headers=get_headers(),
        timeout=30
    )

    response.raise_for_status()

    return response.json()


def review_pull_request(
    owner,
    repo,
    pull_number
):

    files = get_pull_request_files(
        owner,
        repo,
        pull_number
    )

    reviews = []

    for file in files:

        filename = file.get(
            "filename",
            ""
        )

        patch = file.get(
            "patch",
            ""
        )

        if not patch:
            continue

        language = detect_language(
            filename
        )

        if not language:
            continue

        try:

            result = review_code(
                patch,
                language
            )

            reviews.append({
                "file": filename,
                "language": language,
                "risk": result.get(
                    "risk"
                ),
                "recommendation": result.get(
                    "recommendation"
                ),
                "matched_pattern": result.get(
                    "matched_pattern"
                ),
                "suppressed": result.get(
                    "suppressed",
                    False
                )
            })

        except requests.RequestException as error:

            reviews.append({
                "file": filename,
                "language": language,
                "risk": "ERROR",
                "recommendation": str(error),
                "matched_pattern": "",
                "suppressed": False
            })

    return reviews


def create_review_body(reviews):

    if not reviews:
        return (
            "## CodeGuard AI Review\n\n"
            "No supported C/C++/Java code changes "
            "were found in this pull request."
        )

    lines = [
        "## CodeGuard AI – Y2038 Review",
        "",
        "Automated review generated by "
        "CodeGuard AI.",
        ""
    ]

    has_risk = False

    for review in reviews:

        risk = str(
            review.get("risk", "UNKNOWN")
        ).upper()

        if risk not in ["LOW", "NONE", "SAFE"]:
            has_risk = True

        lines.append(
            f"### `{review['file']}`"
        )

        lines.append(
            f"- **Language:** {review['language']}"
        )

        lines.append(
            f"- **Risk:** {risk}"
        )

        lines.append(
            f"- **Suppressed:** "
            f"{review['suppressed']}"
        )

        if review.get(
            "matched_pattern"
        ):

            lines.append(
                f"- **Matched Pattern:** "
                f"`{review['matched_pattern']}`"
            )

        if review.get(
            "recommendation"
        ):

            lines.append(
                f"- **Recommendation:** "
                f"{review['recommendation']}"
            )

        lines.append("")

    if has_risk:
        lines.append(
            "⚠️ **Y2038-related risk detected. "
            "Please review the recommendations above.**"
        )
    else:
        lines.append(
            "✅ **No significant Y2038 risk detected.**"
        )

    return "\n".join(lines)


def post_pull_request_comment(
    owner,
    repo,
    pull_number,
    body
):

    url = (
        f"{GITHUB_API}/repos/"
        f"{owner}/{repo}/issues/"
        f"{pull_number}/comments"
    )

    response = requests.post(
        url,
        headers=get_headers(),
        json={
            "body": body
        },
        timeout=30
    )

    response.raise_for_status()

    return response.json()


def print_reviews(reviews):

    print("\n===================================")
    print("     GITHUB PR CODEGUARD REVIEW")
    print("===================================")

    if not reviews:

        print(
            "No supported code changes found."
        )

        return

    for review in reviews:

        print("\nFile:", review["file"])

        print(
            "Language:",
            review["language"]
        )

        print(
            "Risk:",
            review["risk"]
        )

        print(
            "Suppressed:",
            review["suppressed"]
        )

        if review["recommendation"]:

            print(
                "Recommendation:",
                review["recommendation"]
            )

        if review["matched_pattern"]:

            print(
                "Matched Pattern:",
                review["matched_pattern"]
            )

    print(
        "\n==================================="
    )


if __name__ == "__main__":

    owner = os.getenv(
        "GITHUB_OWNER"
    )

    repo = os.getenv(
        "GITHUB_REPO"
    )

    pull_number = os.getenv(
        "GITHUB_PR_NUMBER"
    )

    post_comment = os.getenv(
        "GITHUB_POST_COMMENT",
        "false"
    ).lower() == "true"

    if not owner or not repo or not pull_number:

        print(
            "Set these environment variables first:"
        )

        print(
            "GITHUB_TOKEN"
        )

        print(
            "GITHUB_OWNER"
        )

        print(
            "GITHUB_REPO"
        )

        print(
            "GITHUB_PR_NUMBER"
        )

        print(
            "Optional: GITHUB_POST_COMMENT=true"
        )

    else:

        reviews = review_pull_request(
            owner,
            repo,
            int(pull_number)
        )

        print_reviews(
            reviews
        )

        review_body = create_review_body(
            reviews
        )

        print(
            "\nGenerated GitHub Review:\n"
        )

        print(
            review_body
        )

        if post_comment:

            post_pull_request_comment(
                owner,
                repo,
                int(pull_number),
                review_body
            )

            print(
                "\nReview comment posted to GitHub."
            )